name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install Dependecies
      - run: npm install
      - name: Lint
      - run: npm run eslint
